import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function GET() {
  try {
    const session = await auth();
    
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const projects = await prisma.project.findMany({
      where: { userId: session.user.id },
      orderBy: { updatedAt: "desc" },
    });

    return NextResponse.json(projects);
  } catch (error) {
    console.error("Error fetching projects:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const session = await auth();
    
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const { name, description, type, framework } = body;

    if (!name || !type || !framework) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      );
    }

    // Default files based on framework
    const defaultFiles = getDefaultFiles(type, framework);

    const project = await prisma.project.create({
      data: {
        name,
        description,
        type,
        framework,
        files: defaultFiles,
        userId: session.user.id,
      },
    });

    return NextResponse.json(project, { status: 201 });
  } catch (error) {
    console.error("Error creating project:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

function getDefaultFiles(type: string, framework: string) {
  if (type === "web") {
    if (framework === "react") {
      return [
        {
          path: "src/App.tsx",
          content: `import React from 'react';

function App() {
  return (
    <div className="min-h-screen bg-gray-100 flex items-center justify-center">
      <h1 className="text-4xl font-bold text-gray-800">
        Welcome to your React App!
      </h1>
    </div>
  );
}

export default App;`,
          language: "typescript",
        },
        {
          path: "src/index.tsx",
          content: `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`,
          language: "typescript",
        },
        {
          path: "src/index.css",
          content: `@tailwind base;
@tailwind components;
@tailwind utilities;`,
          language: "css",
        },
      ];
    } else if (framework === "nextjs") {
      return [
        {
          path: "app/page.tsx",
          content: `export default function Home() {
  return (
    <main className="min-h-screen bg-gray-100 flex items-center justify-center">
      <h1 className="text-4xl font-bold text-gray-800">
        Welcome to your Next.js App!
      </h1>
    </main>
  );
}`,
          language: "typescript",
        },
        {
          path: "app/layout.tsx",
          content: `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by CodeMe',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,
          language: "typescript",
        },
        {
          path: "app/globals.css",
          content: `@tailwind base;
@tailwind components;
@tailwind utilities;`,
          language: "css",
        },
      ];
    }
  } else if (type === "android") {
    if (framework === "react-native") {
      return [
        {
          path: "App.tsx",
          content: `import React from 'react';
import { SafeAreaView, StyleSheet, Text, View } from 'react-native';

function App(): React.JSX.Element {
  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.content}>
        <Text style={styles.title}>Welcome to your React Native App!</Text>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
  },
});

export default App;`,
          language: "typescript",
        },
      ];
    } else if (framework === "flutter") {
      return [
        {
          path: "lib/main.dart",
          content: `import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'My App',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('My App'),
      ),
      body: const Center(
        child: Text(
          'Welcome to your Flutter App!',
          style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
        ),
      ),
    );
  }
}`,
          language: "dart",
        },
      ];
    }
  }

  return [];
}
